#!/usr/bin/env bash
# transfers a file from our client to a server

LOCAL_FILE=$1
SERVER=$2
USERNAME=$3
P_KEY=$4

if [ $# -lt 3 ]
then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
exit 0

scp -o StricktHostKeyChecking=no -i $P_KEY $LOCAL_FILE $USERNAME@$SERVER
