#!/usr/bin/env bash
# find out why nginx is not listening on port 80
# remove the default sites
# create a symbolic link to the default file
# restart nginx server
rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
