#!/usr/bin/env bash
# find out why nginx is not listening on port 80
# remove the default sites
# create a symbolic link to the default file
# restart nginx server
cd /etc/nginx/sites-enabled/ || exit
rm default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
